---
- name: Manage Public API
  hosts: isems-public
  remote_user: pi
  become_method: sudo

  vars:
    certbot_auto_renew_user: "{{ ansible_user }}"
    certbot_auto_renew_hour: 2
    certbot_auto_renew_minute: 10

  roles:
    - role: jdauphant.nginx
      become: true
      nginx_configs:
        gzip:
          - gzip on
        upstream:
          - upstream isems-data-collector { server unix:///tmp/uwsgi-isems-data-collector.sock; }
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        isems:
          - listen 80
          - server_name api.isems.de
          - location / {
              uwsgi_pass   isems-data-collector;
              include      /etc/nginx/uwsgi_params;
              add_header Access-Control-Allow-Origin *;
            }
          - listen 443 ssl # managed by Certbot
          - ssl_certificate /etc/letsencrypt/live/api.isems.de/fullchain.pem # managed by Certbot
          - ssl_certificate_key /etc/letsencrypt/live/api.isems.de/privkey.pem # managed by Certbot
          - include /etc/letsencrypt/options-ssl-nginx.conf # managed by Certbot
          - ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem # managed by Certbot

    - role: geerlingguy.git
      become: true
    - role: geerlingguy.certbot
      become: true
    - flask
