---
- name: install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pip

- name: Clone Data Collector Repository
  git:
    repo: 'https://github.com/ISEMS/isems-data-collector.git'
    dest: "{{ project_path }}"

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present
  become: yes

- name: install requirements
  pip:
    requirements: requirements.txt
    chdir: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"

- name: initizalize database
  command: "env DATABASE_URL={{database_url}} {{ virtualenv_path }}/bin/flask db upgrade"
  args:
      chdir: "{{ project_path }}"

- name: Create uwsgi config
  template:
    src: uwsgi-isems.ini.j2
    dest: /etc/uwsgi/apps-enabled/uwsgi-isems.ini
    backup: yes
  become: yes

- name: Restart uwsgi
  systemd:
    name: uwsgi
    state: restarted
  become: yes

- name: Add cronjob to download Data
  cron:
    name: "update isems-data"
    minute: "*/15"
    job: "env FLASK_APP={{ project_path }}/app.py DATABASE_URL={{database_url}} ISEMS_ROUTER_IPS={{ node_ips | join(',') }} {{ virtualenv_path }}/bin/flask update_data"
