---
project_path: "/home/{{ ansible_ssh_user }}/isems-data-collector"
virtualenv_path: "{{ project_path }}/virtualenv"
database_url: "sqlite:////home/{{ ansible_ssh_user }}/isems-data-collector.sqlite"
node_ips:
  - 10.36.158.33
  - 10.31.1.229
